### PR TITLE
Feature Awesome Books with ES6

### PR DESCRIPTION
**Pull request by gitbygaurav**
## **On this feature branch, the below features have been implemented :-

- The awesome books app is restructured using modules.
- Used ES6 syntax.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @gauravgangwarweb are you submitting for a first review or re-review? I can't see previous comments by the last reviewer

**Comment by gitbygaurav** [comment]
> Hi @gauravgangwarweb are you submitting for a first review or re-review? I can't see previous comments by the last reviewer

Hii @prolajumokeoni  this is my second review as in my previous repo there was some errors from github side like I was not able to push and pull so I deleted that repo and created a new one.
Thanks

**Comment by prolajumokeoni** [comment]
@gauravgangwarweb It would be better to always use the same pr for re-review so the next reviewer can see if the changes requested has been implemented

**Review by prolajumokeoni — APPROVED** [review]
Hi @gauravgangwarweb 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

It would be better to always use the same pr for re-review so the next reviewer can see if the changes requested by previous reviewer has been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gitbygaurav** [comment]
> @gauravgangwarweb It would be better to always use the same pr for re-review so the next reviewer can see if the changes requested has been implemented

Sorry for that,It will not happen in future projects.

**Comment by gitbygaurav** [comment]
> Hi @gauravgangwarweb
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## Highlights
> * No linter errors ✅
> * Github flow was used correctly 🚀
> * Good Pr title and description 💪🏿
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> It would be better to always use the same pr for re-review so the next reviewer can see if the changes requested by previous reviewer has been implemented
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks for approval 😊.

**Pull request merged**
